from shared.models import PROTOCOL_VERSION

SUPPORTED_PROTOCOL_VERSION = PROTOCOL_VERSION
AVAILABLE_WITNESSES = ("A", "B", "C", "D", "E")
WITNESS_QUORUM_SIZE = 3
CHALLENGE_TTL_SECONDS = 30
SESSION_ID_BYTES = 16
NONCE_BYTES = 32
